<?php

namespace AppBundle\Repository;

/**
 * CivilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CivilRepository extends \Doctrine\ORM\EntityRepository
{
}
