<?php

namespace AppBundle\Repository;

/**
 * ContraventionaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContraventionaleRepository extends \Doctrine\ORM\EntityRepository
{
}
