<?php

namespace AppBundle\Repository;

/**
 * PenalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenalRepository extends \Doctrine\ORM\EntityRepository
{
}
